name: habit-website  # sets the Compose project name (Otherwise pulls from directory name)
services:
  habit-website:
  
    build: .

    ports:
      - "8501:8501"  # Maps container's port 8501 to host's 8501

    volumes:
      - ./habits.db:/app/habits.db  # Mount the SQLite DB file from host into container

    working_dir: /app # Not needed here because in dockerfile

    command: uv run main.py 
